// Fable-style HUD data producer. This module is intentionally isolated from
// the main gameplay script so the HUD keeps updating if another system fails.
import { system, world } from "@minecraft/server";

const notices = new Map();
const RADAR_SIZE = 11;
const RADAR_MIDDLE = Math.floor(RADAR_SIZE / 2);
const RADAR_BLOCKS_PER_CELL = 3;

function property(player, key, fallback = 0) {
  try {
    const value = player.getDynamicProperty(key);
    return value === undefined ? fallback : value;
  } catch {
    return fallback;
  }
}

function countItem(player, typeId) {
  const container = player.getComponent("minecraft:inventory")?.container;
  if (!container) return 0;
  let count = 0;
  for (let slot = 0; slot < container.size; slot++) {
    const item = container.getItem(slot);
    if (item?.typeId === typeId) count += item.amount;
  }
  return count;
}

function maxWill(player) {
  return 100 + property(player, "fc_up_magic_power", 0) * 50;
}

function willEnergy(player) {
  return Math.min(maxWill(player), property(player, "fc_will", 100));
}

function scaledWidth(maximum, baseMaximum, perSegment, minimum, cap) {
  const earnedSegments = Math.floor(Math.max(0, maximum - baseMaximum) / perSegment);
  return Math.max(minimum, Math.min(cap, minimum + earnedSegments));
}

// Bars are built from one glyph (U+2588 full block) in two colours so the
// filled and empty runs are guaranteed identical width. The old light-shade
// "░" is not in Bedrock's default font and rendered as a tofu box.
function bar(value, maximum, width, color) {
  const fill = maximum > 0
    ? Math.max(0, Math.min(width, Math.round(value / maximum * width)))
    : 0;
  return `${color}${"█".repeat(fill)}§8${"█".repeat(width - fill)}`;
}

// Private-use radar glyphs authored in font/glyph_E9.png (generated by
// scripts/gen_hud_font.py). Every marker/terrain cell is fixed width so the
// 11x11 grid stays square. The CG variants carry their own in-game colours.
const G = {
  player: "",
  enemy: "",
  friendly: "",
  landmark: "",
  terrain: "",
  water: "",
  tree: "",
  peak: "",
  path: "",
  blank: "",
};

// Baked-colour cells used where Bedrock ignores inline section colours on
// private-use font glyphs.
const CG = {
  ...G,
  player: "\uE910",
  enemy: "\uE911",
  friendly: "\uE912",
  landmark: "\uE913",
  grass: "\uE914",
  water: "\uE915",
  tree: "\uE916",
  peak: "\uE917",
  path: "\uE918",
  blank: "\uE919",
  structure: "\uE91A",
  field: "\uE91B",
  lava: "\uE91C",
  snow: "\uE91D",
  sand: "\uE91E",
  earth: "\uE91F",
  stone: "\uE944",
  lowland: "\uE945",
};

function statusLines(player) {
  const health = player.getComponent("minecraft:health");
  const hp = Math.ceil(health?.currentValue ?? 0);
  const healthBonus = property(player, "fc_up_health", 0) * 4
    + property(player, "fc_bonus_hp", 0);
  const trainedHpMax = 20 + Math.min(24, Math.ceil(healthBonus / 4) * 4);
  const hpMax = Math.ceil(Math.max(health?.effectiveMax ?? 20, trainedHpMax));
  const will = willEnergy(player);
  const willMax = maxWill(player);
  const hunger = player.getComponent("minecraft:player.hunger")
    ?? player.getComponent("minecraft:hunger");
  const food = Math.ceil(hunger?.currentValue ?? 20);
  const foodMax = Math.ceil(hunger?.effectiveMax ?? hunger?.defaultValue ?? 20);
  const multiplier = property(player, "fc_mult", 0);
  return [
    `${bar(hp, hpMax, scaledWidth(hpMax, 20, 4, 12, 26), "§c")} §f${hp}/${hpMax}`,
    `${bar(will, willMax, scaledWidth(willMax, 100, 25, 12, 30), "§9")} §f${will}/${willMax}`,
    `${bar(food, foodMax, 12, "§6")} §f${food}/${foodMax}`,
    // Bedrock collapses truly empty label lines. Keep the row present so every
    // later HUD slicer continues to address the same payload line.
    multiplier > 0 ? `§6× ${multiplier}` : CG.blank,
  ];
}

function canSeePlayer(npc, player, maxDistance) {
  try {
    const head = npc.getHeadLocation?.() ?? {
      x: npc.location.x,
      y: npc.location.y + 1.5,
      z: npc.location.z,
    };
    const target = player.getHeadLocation?.() ?? {
      x: player.location.x,
      y: player.location.y + 1.5,
      z: player.location.z,
    };
    const dx = target.x - head.x;
    const dy = target.y - head.y;
    const dz = target.z - head.z;
    const distance = Math.max(0.001, Math.hypot(dx, dy, dz));
    if (distance > maxDistance) return false;
    const direction = { x: dx / distance, y: dy / distance, z: dz / distance };
    const look = npc.getViewDirection();
    const fieldOfView = player.isSneaking ? 0.55 : 0.25;
    if (look.x * direction.x + look.y * direction.y + look.z * direction.z < fieldOfView) {
      return false;
    }
    try {
      if (npc.dimension.getBlockFromRay(head, direction, {
        maxDistance: Math.max(0, distance - 0.6),
        includeLiquidBlocks: false,
        includePassableBlocks: false,
      })) return false;
    } catch { }
    return true;
  } catch {
    return false;
  }
}

function npcAwarenessState(player) {
  const awarenessDistance = 24;
  const nearbyDistance = 12;
  const sightDistance = player.isSneaking ? 12 : 24;
  const observers = new Map();
  const collect = (query) => {
    try {
      for (const npc of player.dimension.getEntities({
        location: player.location,
        maxDistance: awarenessDistance,
        ...query,
      })) {
        if (npc.id !== player.id) observers.set(npc.id, npc);
      }
    } catch { }
  };
  collect({ families: ["fc_friendly"] });
  collect({ type: "minecraft:npc" });
  collect({ type: "minecraft:villager_v2" });
  collect({ type: "minecraft:villager" });
  try {
    const nearby = [...observers.values()].slice(0, 32);
    if (nearby.some((npc) => canSeePlayer(npc, player, sightDistance))) {
      return "seen";
    }
    if (nearby.some((npc) => {
      const dx = npc.location.x - player.location.x;
      const dy = npc.location.y - player.location.y;
      const dz = npc.location.z - player.location.z;
      return Math.hypot(dx, dy, dz) <= nearbyDistance;
    })) return "nearby";
    return "clear";
  } catch {
    return "clear";
  }
}

function clock() {
  const ticks = ((world.getTimeOfDay() % 24000) + 24000) % 24000;
  const dial = String.fromCodePoint(0xE920 + Math.floor(ticks / 1000));
  return `§f${dial}`;
}

function landmarks() {
  const result = [];
  try {
    const guild = JSON.parse(world.getDynamicProperty("fc_guild_loc") ?? "null");
    if (guild) result.push({ name: "Guild", x: guild.x, z: guild.z });
  } catch { }
  try {
    const sites = JSON.parse(world.getDynamicProperty("fc_cullis") ?? "[]");
    for (const site of sites) result.push(site);
  } catch { }
  return result.filter((entry) => Number.isFinite(entry.x) && Number.isFinite(entry.z));
}

function nearestLandmark(player) {
  let nearest = null;
  for (const marker of landmarks()) {
    const distance = Math.round(Math.hypot(marker.x - player.location.x, marker.z - player.location.z));
    if (!nearest || distance < nearest.distance) nearest = { ...marker, distance };
  }
  return nearest;
}

const DIRECTIONS = ["S", "SW", "W", "NW", "N", "NE", "E", "SE"];
function heading(player) {
  const yaw = ((player.getRotation().y % 360) + 360) % 360;
  return DIRECTIONS[Math.round(yaw / 45) % 8];
}

function horizontalBasis(player) {
  const yaw = player.getRotation().y * Math.PI / 180;
  const forward = { x: -Math.sin(yaw), z: Math.cos(yaw) };
  return {
    forward,
    right: { x: -forward.z, z: forward.x },
  };
}

function terrainGlyph(block, playerY) {
  if (!block) return CG.lowland;
  const id = block.typeId;
  const deltaY = block.location.y - playerY;
  if (id.includes("water") || id.includes("ice")) return CG.water;
  if (id.includes("lava") || id.includes("fire") || id.includes("magma")) return CG.lava;
  if (id.includes("snow")) return CG.snow;
  if (id.includes("sand") || id.includes("sandstone")) return CG.sand;
  if (id.includes("leaves") || id.includes("log") || id.includes("stem")) return CG.tree;
  if (id.includes("farmland") || id.includes("crop") || id.includes("wheat")
    || id.includes("carrot") || id.includes("potato")) return CG.field;
  if (id.includes("plank") || id.includes("brick") || id.includes("terracotta")
    || id.includes("concrete") || id.includes("wool") || id.includes("tile")) {
    return CG.structure;
  }
  if (id.includes("grass") || id.includes("moss") || id.includes("azalea")) return CG.grass;
  if (id.includes("path") || id.includes("cobble") || id.includes("gravel")) return CG.path;
  if (id.includes("stone") || id.includes("ore") || id.includes("deepslate")
    || id.includes("tuff")) return deltaY > 4 ? CG.peak : CG.stone;
  if (id.includes("dirt") || id.includes("mud") || id.includes("clay")) return CG.earth;
  return deltaY > 4 ? CG.peak : deltaY < -4 ? CG.lowland : CG.stone;
}

function radarRows(player) {
  const { forward, right } = horizontalBasis(player);
  const cells = Array.from(
    { length: RADAR_SIZE },
    () => Array(RADAR_SIZE).fill(CG.blank),
  );
  const priorities = Array.from(
    { length: RADAR_SIZE },
    () => Array(RADAR_SIZE).fill(0),
  );

  for (let row = 0; row < RADAR_SIZE; row++) {
    for (let column = 0; column < RADAR_SIZE; column++) {
      const localX = column - RADAR_MIDDLE;
      const localZ = RADAR_MIDDLE - row;
      if (Math.hypot(localX, localZ) > RADAR_MIDDLE + 0.35) continue;
      const x = Math.floor(player.location.x
        + right.x * localX * RADAR_BLOCKS_PER_CELL
        + forward.x * localZ * RADAR_BLOCKS_PER_CELL);
      const z = Math.floor(player.location.z
        + right.z * localX * RADAR_BLOCKS_PER_CELL
        + forward.z * localZ * RADAR_BLOCKS_PER_CELL);
      try {
        cells[row][column] = terrainGlyph(player.dimension.getTopmostBlock({ x, z }), player.location.y);
      } catch {
        try {
          cells[row][column] = terrainGlyph(
            player.dimension.getBlock({ x, y: Math.floor(player.location.y) - 1, z }),
            player.location.y,
          );
        } catch { }
      }
    }
  }

  const place = (location, glyph, priority, clamp = false) => {
    const dx = location.x - player.location.x;
    const dz = location.z - player.location.z;
    let localX = (dx * right.x + dz * right.z) / RADAR_BLOCKS_PER_CELL;
    let localZ = (dx * forward.x + dz * forward.z) / RADAR_BLOCKS_PER_CELL;
    if (clamp) {
      const distance = Math.hypot(localX, localZ);
      if (distance > RADAR_MIDDLE) {
        localX *= RADAR_MIDDLE / distance;
        localZ *= RADAR_MIDDLE / distance;
      }
    }
    const column = RADAR_MIDDLE + Math.round(localX);
    const row = RADAR_MIDDLE - Math.round(localZ);
    if (row < 0 || row >= RADAR_SIZE || column < 0 || column >= RADAR_SIZE) return;
    if (priority < priorities[row][column]) return;
    cells[row][column] = glyph;
    priorities[row][column] = priority;
  };

  for (const marker of landmarks()) place(marker, CG.landmark, 1, true);
  try {
    for (const npc of player.dimension.getEntities({
      location: player.location,
      maxDistance: RADAR_MIDDLE * RADAR_BLOCKS_PER_CELL + 2,
      families: ["fc_friendly"],
    })) place(npc.location, CG.friendly, 2);
  } catch { }
  try {
    for (const hostile of player.dimension.getEntities({
      location: player.location,
      maxDistance: RADAR_MIDDLE * RADAR_BLOCKS_PER_CELL + 2,
      families: ["monster"],
    })) place(hostile.location, CG.enemy, 3);
  } catch { }
  cells[RADAR_MIDDLE][RADAR_MIDDLE] = CG.player;
  // Fixed-width glyphs are joined with no separator so every row is exactly
  // RADAR_SIZE cells wide and the grid cannot shear.
  return cells.map((row) => `§f${row.join("")}`);
}

function radarLines(player) {
  const awareness = npcAwarenessState(player);
  const nearest = nearestLandmark(player);
  const nav = nearest
    ? `${heading(player)} §8· §6${nearest.name} §8· §f${nearest.distance}m`
    : `${heading(player)} §8· §f${Math.floor(player.location.x)}, ${Math.floor(player.location.z)}`;
  const eyeGlyph = awareness === "seen"
    ? "\uE900"
    : awareness === "nearby"
      ? "\uE902"
      : "\uE901";
  // The eye and day dial are single 16px glyphs. A glyph cell renders taller
  // than one line pitch, so a CG.blank spacer line sits below each one; without
  // it the dial bleeds into the eye window and the first green radar row bleeds
  // into the dial window (the "green box"). The spacers absorb that overhang so
  // each ornament reads as its own clean icon. Reordering here shifts every clip
  // offset below — keep hud_screen.json / audit_hud.py PAYLOAD_LINE in lockstep.
  return [
    `§f${eyeGlyph}`,
    CG.blank,
    clock(),
    CG.blank,
    ...radarRows(player),
    `§e${nav}`,
  ];
}

function wantedStars(player) {
  const heat = Math.max(0, Math.min(5, Math.floor(property(player, "fc_wanted_heat", 0))));
  return heat > 0 ? `§f${"\uE946".repeat(heat)}` : CG.blank;
}

function payload(player) {
  const notice = notices.get(player.id);
  const noticeActive = notice && system.currentTick < notice.until;
  const noticeText = noticeActive ? notice.text : CG.blank;
  if (notice && !noticeActive) notices.delete(player.id);
  return [
    ...statusLines(player),
    ...radarLines(player),
    // Line 20 is intentionally coin-only. Map/navigation details live on
    // line 19 beneath the minimap and must never share the purse panel.
    `§6${countItem(player, "fc:gold_coin")}`,
    noticeText,
    wantedStars(player),
  ].join("\n");
}

export function showHudNotice(player, text, holdTicks = 30) {
  notices.set(player.id, { text, until: system.currentTick + holdTicks });
}

system.runInterval(() => {
  for (const player of world.getPlayers()) {
    try { player.onScreenDisplay.setActionBar(payload(player)); } catch { }
  }
}, 10);
