// Generated by scripts/gen_emotes.py. Do not edit by hand.
export const FABLE_EMOTES = [
  {
    "id": "belch",
    "name": "Belch",
    "category": "funny",
    "unlock": {
      "type": "start"
    },
    "effect": {
      "loveHate": -1,
      "fearFunny": -7,
      "uglyAttractive": -2,
      "morality": -1
    },
    "animation": "animation.fable.player.belch",
    "template": "belch",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "fart",
    "name": "Fart",
    "category": "funny",
    "unlock": {
      "type": "start"
    },
    "effect": {
      "loveHate": -2,
      "fearFunny": -10,
      "uglyAttractive": -3,
      "morality": -1
    },
    "animation": "animation.fable.player.fart",
    "template": "fart",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "follow",
    "name": "Follow",
    "category": "friendly",
    "unlock": {
      "type": "start"
    },
    "effect": {
      "loveHate": 4,
      "fearFunny": -1,
      "uglyAttractive": 0,
      "morality": 1
    },
    "animation": "animation.fable.player.follow",
    "template": "beckon",
    "durationTicks": 40,
    "functional": "follow",
    "nativePersonaPieceIds": []
  },
  {
    "id": "wait",
    "name": "Wait",
    "category": "friendly",
    "unlock": {
      "type": "start"
    },
    "effect": {
      "loveHate": 1,
      "fearFunny": 0,
      "uglyAttractive": 0,
      "morality": 0
    },
    "animation": "animation.fable.player.wait",
    "template": "halt",
    "durationTicks": 40,
    "functional": "wait",
    "nativePersonaPieceIds": []
  },
  {
    "id": "giggle",
    "name": "Giggle",
    "category": "funny",
    "unlock": {
      "type": "start"
    },
    "effect": {
      "loveHate": 2,
      "fearFunny": -7,
      "uglyAttractive": 1,
      "morality": 1
    },
    "animation": "animation.fable.player.giggle",
    "template": "laugh",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "flirt",
    "name": "Flirt",
    "category": "romantic",
    "unlock": {
      "type": "start"
    },
    "effect": {
      "loveHate": 10,
      "fearFunny": -2,
      "uglyAttractive": 7,
      "morality": 2
    },
    "animation": "animation.fable.player.flirt",
    "template": "flirt",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "cossack_dance",
    "name": "Cossack Dance",
    "category": "funny",
    "unlock": {
      "type": "start"
    },
    "effect": {
      "loveHate": 3,
      "fearFunny": -10,
      "uglyAttractive": 2,
      "morality": 1
    },
    "animation": "animation.fable.player.cossack_dance",
    "template": "cossack",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "sneer",
    "name": "Sneer",
    "category": "scary",
    "unlock": {
      "type": "renown",
      "rank": 1,
      "value": 100
    },
    "effect": {
      "loveHate": -3,
      "fearFunny": 8,
      "uglyAttractive": -1,
      "morality": -2
    },
    "animation": "animation.fable.player.sneer",
    "template": "sneer",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "manly_arm_pump",
    "name": "Manly Arm Pump",
    "category": "scary",
    "unlock": {
      "type": "renown",
      "rank": 2,
      "value": 300
    },
    "effect": {
      "loveHate": 2,
      "fearFunny": 5,
      "uglyAttractive": 4,
      "morality": 0
    },
    "animation": "animation.fable.player.manly_arm_pump",
    "template": "arm_pump",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "scary_laugh",
    "name": "Scary Laugh",
    "category": "scary",
    "unlock": {
      "type": "renown",
      "rank": 3,
      "value": 700
    },
    "effect": {
      "loveHate": -3,
      "fearFunny": 12,
      "uglyAttractive": -1,
      "morality": -3
    },
    "animation": "animation.fable.player.scary_laugh",
    "template": "scary_laugh",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "sexy_hero_pose",
    "name": "Sexy Hero Pose",
    "category": "romantic",
    "unlock": {
      "type": "renown",
      "rank": 4,
      "value": 1200
    },
    "effect": {
      "loveHate": 8,
      "fearFunny": -1,
      "uglyAttractive": 10,
      "morality": 0
    },
    "animation": "animation.fable.player.sexy_hero_pose",
    "template": "hero_pose",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "blood_lust_roar",
    "name": "Blood Lust Roar",
    "category": "scary",
    "unlock": {
      "type": "renown",
      "rank": 5,
      "value": 2000
    },
    "effect": {
      "loveHate": -6,
      "fearFunny": 16,
      "uglyAttractive": 1,
      "morality": -5
    },
    "animation": "animation.fable.player.blood_lust_roar",
    "template": "roar",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "apologise",
    "name": "Apologise",
    "category": "friendly",
    "unlock": {
      "type": "alignment",
      "min": 150
    },
    "effect": {
      "loveHate": 9,
      "fearFunny": -1,
      "uglyAttractive": 2,
      "morality": 4
    },
    "animation": "animation.fable.player.apologise",
    "template": "apologise",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "air_guitar",
    "name": "Air Guitar",
    "category": "funny",
    "unlock": {
      "type": "alignment",
      "max": -150
    },
    "effect": {
      "loveHate": 1,
      "fearFunny": -8,
      "uglyAttractive": 1,
      "morality": -2
    },
    "animation": "animation.fable.player.air_guitar",
    "template": "air_guitar",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "thanks",
    "name": "Thanks",
    "category": "friendly",
    "unlock": {
      "type": "alignment",
      "min": 400
    },
    "effect": {
      "loveHate": 8,
      "fearFunny": -1,
      "uglyAttractive": 2,
      "morality": 3
    },
    "animation": "animation.fable.player.thanks",
    "template": "thanks",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "flamenco_dance",
    "name": "Flamenco Dance",
    "category": "funny",
    "unlock": {
      "type": "alignment",
      "min": 400
    },
    "effect": {
      "loveHate": 4,
      "fearFunny": -9,
      "uglyAttractive": 4,
      "morality": 2
    },
    "animation": "animation.fable.player.flamenco_dance",
    "template": "flamenco",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "middle_finger",
    "name": "Middle Finger",
    "category": "rude",
    "unlock": {
      "type": "alignment",
      "max": -400
    },
    "effect": {
      "loveHate": -12,
      "fearFunny": 2,
      "uglyAttractive": -4,
      "morality": -8
    },
    "animation": "animation.fable.player.middle_finger",
    "template": "rude",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "crotch_grab",
    "name": "Crotch Grab",
    "category": "funny",
    "unlock": {
      "type": "alignment",
      "min": 750
    },
    "effect": {
      "loveHate": -2,
      "fearFunny": -9,
      "uglyAttractive": -3,
      "morality": 1
    },
    "animation": "animation.fable.player.crotch_grab",
    "template": "crotch",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "disco_dance",
    "name": "Disco Dance",
    "category": "funny",
    "unlock": {
      "type": "alignment",
      "min": 750
    },
    "effect": {
      "loveHate": 4,
      "fearFunny": -11,
      "uglyAttractive": 4,
      "morality": 2
    },
    "animation": "animation.fable.player.disco_dance",
    "template": "disco",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "vulgar_thrust",
    "name": "Vulgar Thrust",
    "category": "rude",
    "unlock": {
      "type": "alignment",
      "max": -750
    },
    "effect": {
      "loveHate": -15,
      "fearFunny": 4,
      "uglyAttractive": -7,
      "morality": -10
    },
    "animation": "animation.fable.player.vulgar_thrust",
    "template": "vulgar",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "kiss_my_ass",
    "name": "Kiss My Ass",
    "category": "rude",
    "unlock": {
      "type": "alignment",
      "max": -400
    },
    "effect": {
      "loveHate": -11,
      "fearFunny": -2,
      "uglyAttractive": -5,
      "morality": -7
    },
    "animation": "animation.fable.player.kiss_my_ass",
    "template": "kiss_ass",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "tap_dance",
    "name": "Tap Dance",
    "category": "funny",
    "unlock": {
      "type": "alignment",
      "min": 400
    },
    "effect": {
      "loveHate": 3,
      "fearFunny": -9,
      "uglyAttractive": 3,
      "morality": 2
    },
    "animation": "animation.fable.player.tap_dance",
    "template": "tap",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "steal",
    "name": "Steal",
    "category": "criminal",
    "unlock": {
      "type": "guile",
      "level": 3,
      "xp": 2200
    },
    "effect": {
      "loveHate": -9,
      "fearFunny": 3,
      "uglyAttractive": -2,
      "morality": -12
    },
    "animation": "animation.fable.player.steal",
    "template": "steal",
    "durationTicks": 40,
    "functional": "steal",
    "nativePersonaPieceIds": []
  },
  {
    "id": "lockpick",
    "name": "Lockpick",
    "category": "criminal",
    "unlock": {
      "type": "guile",
      "level": 6,
      "xp": 27400
    },
    "effect": {
      "loveHate": -5,
      "fearFunny": 2,
      "uglyAttractive": 0,
      "morality": -8
    },
    "animation": "animation.fable.player.lockpick",
    "template": "lockpick",
    "durationTicks": 40,
    "functional": "lockpick",
    "nativePersonaPieceIds": []
  },
  {
    "id": "yeron",
    "name": "Yeron",
    "category": "oracle",
    "unlock": {
      "type": "quest",
      "quest": "find_the_oracle"
    },
    "effect": {
      "loveHate": 1,
      "fearFunny": 1,
      "uglyAttractive": 1,
      "morality": 0
    },
    "animation": "animation.fable.player.yeron",
    "template": "oracle_yeron",
    "durationTicks": 40,
    "functional": "oracle",
    "nativePersonaPieceIds": []
  },
  {
    "id": "moryk",
    "name": "Moryk",
    "category": "oracle",
    "unlock": {
      "type": "quest",
      "quest": "find_the_oracle"
    },
    "effect": {
      "loveHate": 1,
      "fearFunny": -1,
      "uglyAttractive": 1,
      "morality": 0
    },
    "animation": "animation.fable.player.moryk",
    "template": "oracle_moryk",
    "durationTicks": 40,
    "functional": "oracle",
    "nativePersonaPieceIds": []
  },
  {
    "id": "calran",
    "name": "Calran",
    "category": "oracle",
    "unlock": {
      "type": "quest",
      "quest": "find_the_oracle"
    },
    "effect": {
      "loveHate": 1,
      "fearFunny": 1,
      "uglyAttractive": 0,
      "morality": 0
    },
    "animation": "animation.fable.player.calran",
    "template": "oracle_calran",
    "durationTicks": 40,
    "functional": "oracle",
    "nativePersonaPieceIds": []
  },
  {
    "id": "avisto",
    "name": "Avisto",
    "category": "oracle",
    "unlock": {
      "type": "quest",
      "quest": "find_the_oracle"
    },
    "effect": {
      "loveHate": 2,
      "fearFunny": 0,
      "uglyAttractive": 1,
      "morality": 0
    },
    "animation": "animation.fable.player.avisto",
    "template": "oracle_avisto",
    "durationTicks": 40,
    "functional": "oracle",
    "nativePersonaPieceIds": []
  },
  {
    "id": "ballet_dance",
    "name": "Ballet Dance",
    "category": "funny",
    "unlock": {
      "type": "alignment",
      "min": 900
    },
    "effect": {
      "loveHate": 5,
      "fearFunny": -8,
      "uglyAttractive": 8,
      "morality": 3
    },
    "animation": "animation.fable.player.ballet_dance",
    "template": "ballet",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "cock_a_doodle_doo",
    "name": "Cock-A-Doodle-Doo",
    "category": "funny",
    "unlock": {
      "type": "challenge",
      "flag": "fc_chicken_champion"
    },
    "effect": {
      "loveHate": 2,
      "fearFunny": -12,
      "uglyAttractive": -1,
      "morality": 0
    },
    "animation": "animation.fable.player.cock_a_doodle_doo",
    "template": "chicken",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  },
  {
    "id": "insult",
    "name": "Insult",
    "category": "rude",
    "unlock": {
      "type": "alignment",
      "max": -400
    },
    "effect": {
      "loveHate": -12,
      "fearFunny": 3,
      "uglyAttractive": -3,
      "morality": -8
    },
    "animation": "animation.fable.player.insult",
    "template": "insult",
    "durationTicks": 40,
    "functional": "social",
    "nativePersonaPieceIds": []
  }
];
export const FABLE_EMOTE_BY_ID = new Map(FABLE_EMOTES.map((entry) => [entry.id, entry]));
