// AUTO-GENERATED by gen_behavior.py — do not edit.
export const DATA = {
 "weapons": {
  "fc:iron_longsword": {
   "fable": 27,
   "slots": 0,
   "augments": [],
   "cat": "melee"
  },
  "fc:iron_katana": {
   "fable": 21,
   "slots": 0,
   "augments": [],
   "cat": "melee"
  },
  "fc:iron_cleaver": {
   "fable": 25,
   "slots": 0,
   "augments": [],
   "cat": "melee"
  },
  "fc:iron_axe": {
   "fable": 29,
   "slots": 0,
   "augments": [],
   "cat": "melee"
  },
  "fc:iron_mace": {
   "fable": 28,
   "slots": 0,
   "augments": [],
   "cat": "melee"
  },
  "fc:iron_pickhammer": {
   "fable": 30,
   "slots": 0,
   "augments": [],
   "cat": "melee"
  },
  "fc:iron_greataxe": {
   "fable": 36,
   "slots": 0,
   "augments": [],
   "cat": "melee"
  },
  "fc:iron_greatsword": {
   "fable": 34,
   "slots": 0,
   "augments": [],
   "cat": "melee"
  },
  "fc:iron_greathammer": {
   "fable": 40,
   "slots": 0,
   "augments": [],
   "cat": "melee"
  },
  "fc:steel_longsword": {
   "fable": 51,
   "slots": 1,
   "augments": [],
   "cat": "melee"
  },
  "fc:steel_katana": {
   "fable": 40,
   "slots": 1,
   "augments": [],
   "cat": "melee"
  },
  "fc:steel_cleaver": {
   "fable": 48,
   "slots": 1,
   "augments": [],
   "cat": "melee"
  },
  "fc:steel_axe": {
   "fable": 54,
   "slots": 1,
   "augments": [],
   "cat": "melee"
  },
  "fc:steel_mace": {
   "fable": 53,
   "slots": 1,
   "augments": [],
   "cat": "melee"
  },
  "fc:steel_pickhammer": {
   "fable": 56,
   "slots": 1,
   "augments": [],
   "cat": "melee"
  },
  "fc:steel_greataxe": {
   "fable": 68,
   "slots": 1,
   "augments": [],
   "cat": "melee"
  },
  "fc:steel_greatsword": {
   "fable": 65,
   "slots": 1,
   "augments": [],
   "cat": "melee"
  },
  "fc:steel_greathammer": {
   "fable": 76,
   "slots": 1,
   "augments": [],
   "cat": "melee"
  },
  "fc:obsidian_longsword": {
   "fable": 90,
   "slots": 2,
   "augments": [],
   "cat": "melee"
  },
  "fc:obsidian_katana": {
   "fable": 70,
   "slots": 2,
   "augments": [],
   "cat": "melee"
  },
  "fc:obsidian_cleaver": {
   "fable": 84,
   "slots": 2,
   "augments": [],
   "cat": "melee"
  },
  "fc:obsidian_axe": {
   "fable": 96,
   "slots": 2,
   "augments": [],
   "cat": "melee"
  },
  "fc:obsidian_mace": {
   "fable": 93,
   "slots": 2,
   "augments": [],
   "cat": "melee"
  },
  "fc:obsidian_pickhammer": {
   "fable": 99,
   "slots": 2,
   "augments": [],
   "cat": "melee"
  },
  "fc:obsidian_greataxe": {
   "fable": 120,
   "slots": 2,
   "augments": [],
   "cat": "melee"
  },
  "fc:obsidian_greatsword": {
   "fable": 114,
   "slots": 2,
   "augments": [],
   "cat": "melee"
  },
  "fc:obsidian_greathammer": {
   "fable": 135,
   "slots": 2,
   "augments": [],
   "cat": "melee"
  },
  "fc:master_longsword": {
   "fable": 135,
   "slots": 3,
   "augments": [],
   "cat": "melee"
  },
  "fc:master_katana": {
   "fable": 105,
   "slots": 3,
   "augments": [],
   "cat": "melee"
  },
  "fc:master_cleaver": {
   "fable": 126,
   "slots": 3,
   "augments": [],
   "cat": "melee"
  },
  "fc:master_axe": {
   "fable": 144,
   "slots": 3,
   "augments": [],
   "cat": "melee"
  },
  "fc:master_mace": {
   "fable": 140,
   "slots": 3,
   "augments": [],
   "cat": "melee"
  },
  "fc:master_pickhammer": {
   "fable": 148,
   "slots": 3,
   "augments": [],
   "cat": "melee"
  },
  "fc:master_greataxe": {
   "fable": 180,
   "slots": 3,
   "augments": [],
   "cat": "melee"
  },
  "fc:master_greatsword": {
   "fable": 171,
   "slots": 3,
   "augments": [],
   "cat": "melee"
  },
  "fc:master_greathammer": {
   "fable": 202,
   "slots": 3,
   "augments": [],
   "cat": "melee"
  },
  "fc:yew_longbow": {
   "fable": 22,
   "slots": 0,
   "augments": [],
   "cat": "ranged"
  },
  "fc:yew_crossbow": {
   "fable": 30,
   "slots": 0,
   "augments": [],
   "cat": "ranged"
  },
  "fc:oak_longbow": {
   "fable": 38,
   "slots": 1,
   "augments": [],
   "cat": "ranged"
  },
  "fc:oak_crossbow": {
   "fable": 51,
   "slots": 1,
   "augments": [],
   "cat": "ranged"
  },
  "fc:ebony_longbow": {
   "fable": 65,
   "slots": 2,
   "augments": [],
   "cat": "ranged"
  },
  "fc:ebony_crossbow": {
   "fable": 88,
   "slots": 2,
   "augments": [],
   "cat": "ranged"
  },
  "fc:master_longbow": {
   "fable": 95,
   "slots": 3,
   "augments": [],
   "cat": "ranged"
  },
  "fc:master_crossbow": {
   "fable": 128,
   "slots": 3,
   "augments": [],
   "cat": "ranged"
  },
  "fc:sword_of_aeons": {
   "fable": 230,
   "slots": 0,
   "augments": [
    "health",
    "mana",
    "sharpening"
   ],
   "cat": "melee"
  },
  "fc:avos_tear": {
   "fable": 230,
   "slots": 0,
   "augments": [
    "health",
    "mana",
    "sharpening"
   ],
   "cat": "melee"
  },
  "fc:the_harbinger": {
   "fable": 180,
   "slots": 0,
   "augments": [
    "silver",
    "health"
   ],
   "cat": "melee"
  },
  "fc:solus_greatsword": {
   "fable": 190,
   "slots": 0,
   "augments": [
    "flame"
   ],
   "cat": "melee"
  },
  "fc:arkens_crossbow": {
   "fable": 220,
   "slots": 0,
   "augments": [
    "piercing",
    "lightning"
   ],
   "cat": "ranged"
  },
  "fc:the_bereaver": {
   "fable": 190,
   "slots": 0,
   "augments": [
    "sharpening",
    "experience"
   ],
   "cat": "melee"
  },
  "fc:avenger": {
   "fable": 180,
   "slots": 0,
   "augments": [
    "sharpening",
    "health"
   ],
   "cat": "melee"
  },
  "fc:orkons_club": {
   "fable": 150,
   "slots": 0,
   "augments": [
    "flame"
   ],
   "cat": "melee"
  },
  "fc:dollmasters_mace": {
   "fable": 160,
   "slots": 0,
   "augments": [
    "mana",
    "lightning"
   ],
   "cat": "melee"
  },
  "fc:wellows_pickhammer": {
   "fable": 142,
   "slots": 0,
   "augments": [
    "piercing",
    "experience"
   ],
   "cat": "melee"
  },
  "fc:katana_hiryu": {
   "fable": 155,
   "slots": 0,
   "augments": [
    "health"
   ],
   "cat": "melee"
  },
  "fc:the_avenger_bow": {
   "fable": 185,
   "slots": 0,
   "augments": [
    "silver",
    "experience"
   ],
   "cat": "ranged"
  },
  "fc:scimitar": {
   "fable": 112,
   "slots": 0,
   "augments": [],
   "cat": "melee"
  },
  "fc:stick": {
   "fable": 20,
   "slots": 0,
   "augments": [],
   "cat": "melee"
  }
 },
 "armor": {
  "fc:apprentice_helm": {
   "align": 0,
   "attract": 0,
   "scary": 0,
   "set": "apprentice",
   "slot": "helm"
  },
  "fc:apprentice_torso": {
   "align": 0,
   "attract": 0,
   "scary": 0,
   "set": "apprentice",
   "slot": "torso"
  },
  "fc:apprentice_legs": {
   "align": 0,
   "attract": 0,
   "scary": 0,
   "set": "apprentice",
   "slot": "legs"
  },
  "fc:apprentice_boots": {
   "align": 0,
   "attract": 0,
   "scary": 0,
   "set": "apprentice",
   "slot": "boots"
  },
  "fc:villager_helm": {
   "align": 0,
   "attract": 5,
   "scary": 0,
   "set": "villager",
   "slot": "helm"
  },
  "fc:villager_torso": {
   "align": 0,
   "attract": 5,
   "scary": 0,
   "set": "villager",
   "slot": "torso"
  },
  "fc:villager_legs": {
   "align": 0,
   "attract": 5,
   "scary": 0,
   "set": "villager",
   "slot": "legs"
  },
  "fc:villager_boots": {
   "align": 0,
   "attract": 5,
   "scary": 0,
   "set": "villager",
   "slot": "boots"
  },
  "fc:leather_bright_helm": {
   "align": 1,
   "attract": 15,
   "scary": 0,
   "set": "leather_bright",
   "slot": "helm"
  },
  "fc:leather_bright_torso": {
   "align": 1,
   "attract": 15,
   "scary": 0,
   "set": "leather_bright",
   "slot": "torso"
  },
  "fc:leather_bright_legs": {
   "align": 1,
   "attract": 15,
   "scary": 0,
   "set": "leather_bright",
   "slot": "legs"
  },
  "fc:leather_bright_boots": {
   "align": 1,
   "attract": 15,
   "scary": 0,
   "set": "leather_bright",
   "slot": "boots"
  },
  "fc:leather_dark_helm": {
   "align": -1,
   "attract": 0,
   "scary": 15,
   "set": "leather_dark",
   "slot": "helm"
  },
  "fc:leather_dark_torso": {
   "align": -1,
   "attract": 0,
   "scary": 15,
   "set": "leather_dark",
   "slot": "torso"
  },
  "fc:leather_dark_legs": {
   "align": -1,
   "attract": 0,
   "scary": 15,
   "set": "leather_dark",
   "slot": "legs"
  },
  "fc:leather_dark_boots": {
   "align": -1,
   "attract": 0,
   "scary": 15,
   "set": "leather_dark",
   "slot": "boots"
  },
  "fc:chainmail_bright_helm": {
   "align": 1,
   "attract": 10,
   "scary": 0,
   "set": "chainmail_bright",
   "slot": "helm"
  },
  "fc:chainmail_bright_torso": {
   "align": 1,
   "attract": 10,
   "scary": 0,
   "set": "chainmail_bright",
   "slot": "torso"
  },
  "fc:chainmail_bright_legs": {
   "align": 1,
   "attract": 10,
   "scary": 0,
   "set": "chainmail_bright",
   "slot": "legs"
  },
  "fc:chainmail_bright_boots": {
   "align": 1,
   "attract": 10,
   "scary": 0,
   "set": "chainmail_bright",
   "slot": "boots"
  },
  "fc:chainmail_dark_helm": {
   "align": -1,
   "attract": 0,
   "scary": 10,
   "set": "chainmail_dark",
   "slot": "helm"
  },
  "fc:chainmail_dark_torso": {
   "align": -1,
   "attract": 0,
   "scary": 10,
   "set": "chainmail_dark",
   "slot": "torso"
  },
  "fc:chainmail_dark_legs": {
   "align": -1,
   "attract": 0,
   "scary": 10,
   "set": "chainmail_dark",
   "slot": "legs"
  },
  "fc:chainmail_dark_boots": {
   "align": -1,
   "attract": 0,
   "scary": 10,
   "set": "chainmail_dark",
   "slot": "boots"
  },
  "fc:platemail_helm": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "platemail",
   "slot": "helm"
  },
  "fc:platemail_torso": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "platemail",
   "slot": "torso"
  },
  "fc:platemail_legs": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "platemail",
   "slot": "legs"
  },
  "fc:platemail_boots": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "platemail",
   "slot": "boots"
  },
  "fc:guard_bowerstone_helm": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "guard_bowerstone",
   "slot": "helm"
  },
  "fc:guard_bowerstone_torso": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "guard_bowerstone",
   "slot": "torso"
  },
  "fc:guard_bowerstone_legs": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "guard_bowerstone",
   "slot": "legs"
  },
  "fc:guard_bowerstone_boots": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "guard_bowerstone",
   "slot": "boots"
  },
  "fc:guard_oakvale_helm": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "guard_oakvale",
   "slot": "helm"
  },
  "fc:guard_oakvale_torso": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "guard_oakvale",
   "slot": "torso"
  },
  "fc:guard_oakvale_legs": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "guard_oakvale",
   "slot": "legs"
  },
  "fc:guard_oakvale_boots": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "guard_oakvale",
   "slot": "boots"
  },
  "fc:guard_snowspire_helm": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "guard_snowspire",
   "slot": "helm"
  },
  "fc:guard_snowspire_torso": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "guard_snowspire",
   "slot": "torso"
  },
  "fc:guard_snowspire_legs": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "guard_snowspire",
   "slot": "legs"
  },
  "fc:guard_snowspire_boots": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "guard_snowspire",
   "slot": "boots"
  },
  "fc:assassin_helm": {
   "align": -1,
   "attract": 0,
   "scary": 25,
   "set": "assassin",
   "slot": "helm"
  },
  "fc:assassin_torso": {
   "align": -1,
   "attract": 0,
   "scary": 25,
   "set": "assassin",
   "slot": "torso"
  },
  "fc:assassin_legs": {
   "align": -1,
   "attract": 0,
   "scary": 25,
   "set": "assassin",
   "slot": "legs"
  },
  "fc:assassin_boots": {
   "align": -1,
   "attract": 0,
   "scary": 25,
   "set": "assassin",
   "slot": "boots"
  },
  "fc:fire_assassin_helm": {
   "align": -1,
   "attract": 0,
   "scary": 30,
   "set": "fire_assassin",
   "slot": "helm"
  },
  "fc:fire_assassin_torso": {
   "align": -1,
   "attract": 0,
   "scary": 30,
   "set": "fire_assassin",
   "slot": "torso"
  },
  "fc:fire_assassin_legs": {
   "align": -1,
   "attract": 0,
   "scary": 30,
   "set": "fire_assassin",
   "slot": "legs"
  },
  "fc:fire_assassin_boots": {
   "align": -1,
   "attract": 0,
   "scary": 30,
   "set": "fire_assassin",
   "slot": "boots"
  },
  "fc:archon_helm": {
   "align": 1,
   "attract": 30,
   "scary": 0,
   "set": "archon",
   "slot": "helm"
  },
  "fc:archon_torso": {
   "align": 1,
   "attract": 30,
   "scary": 0,
   "set": "archon",
   "slot": "torso"
  },
  "fc:archon_legs": {
   "align": 1,
   "attract": 30,
   "scary": 0,
   "set": "archon",
   "slot": "legs"
  },
  "fc:archon_boots": {
   "align": 1,
   "attract": 30,
   "scary": 0,
   "set": "archon",
   "slot": "boots"
  },
  "fc:holy_warrior_helm": {
   "align": 1,
   "attract": 20,
   "scary": 0,
   "set": "holy_warrior_helm",
   "slot": "helm"
  },
  "fc:demon_helm": {
   "align": -1,
   "attract": 0,
   "scary": 35,
   "set": "demon_helm",
   "slot": "helm"
  },
  "fc:pimp_hat": {
   "align": 0,
   "attract": 40,
   "scary": 0,
   "set": "pimp_hat",
   "slot": "helm"
  },
  "fc:wizard_hat": {
   "align": 0,
   "attract": 5,
   "scary": 5,
   "set": "wizard_hat",
   "slot": "helm"
  },
  "fc:bright_wizard_hat": {
   "align": 1,
   "attract": 15,
   "scary": 0,
   "set": "bright_wizard_hat",
   "slot": "helm"
  },
  "fc:dark_wizard_hat": {
   "align": -1,
   "attract": 0,
   "scary": 15,
   "set": "dark_wizard_hat",
   "slot": "helm"
  }
 },
 "consumables": {
  "fc:health_potion": {
   "heal": 8,
   "will": 0,
   "food": 0,
   "morality": 0,
   "xp": null,
   "xp_amount": 0,
   "max_hp": 0,
   "phial": false
  },
  "fc:great_health_potion": {
   "heal": 20,
   "will": 0,
   "food": 0,
   "morality": 0,
   "xp": null,
   "xp_amount": 0,
   "max_hp": 0,
   "phial": false
  },
  "fc:will_potion": {
   "heal": 0,
   "will": 40,
   "food": 0,
   "morality": 0,
   "xp": null,
   "xp_amount": 0,
   "max_hp": 0,
   "phial": false
  },
  "fc:great_will_potion": {
   "heal": 0,
   "will": 100,
   "food": 0,
   "morality": 0,
   "xp": null,
   "xp_amount": 0,
   "max_hp": 0,
   "phial": false
  },
  "fc:resurrection_phial": {
   "heal": 40,
   "will": 100,
   "food": 0,
   "morality": 0,
   "xp": null,
   "xp_amount": 0,
   "max_hp": 0,
   "phial": true
  },
  "fc:ages_of_might_potion": {
   "heal": 0,
   "will": 0,
   "food": 0,
   "morality": 0,
   "xp": "strength",
   "xp_amount": 500,
   "max_hp": 0,
   "phial": false
  },
  "fc:ages_of_skill_potion": {
   "heal": 0,
   "will": 0,
   "food": 0,
   "morality": 0,
   "xp": "skill",
   "xp_amount": 500,
   "max_hp": 0,
   "phial": false
  },
  "fc:ages_of_will_potion": {
   "heal": 0,
   "will": 0,
   "food": 0,
   "morality": 0,
   "xp": "will",
   "xp_amount": 500,
   "max_hp": 0,
   "phial": false
  },
  "fc:elixir_of_life": {
   "heal": 40,
   "will": 0,
   "food": 0,
   "morality": 0,
   "xp": null,
   "xp_amount": 0,
   "max_hp": 2,
   "phial": false
  },
  "fc:crunchy_chick": {
   "heal": 0,
   "will": 0,
   "food": 2,
   "morality": -15,
   "xp": null,
   "xp_amount": 0,
   "max_hp": 0,
   "phial": false
  },
  "fc:tofu": {
   "heal": 0,
   "will": 0,
   "food": 3,
   "morality": 5,
   "xp": null,
   "xp_amount": 0,
   "max_hp": 0,
   "phial": false
  },
  "fc:red_meat": {
   "heal": 0,
   "will": 0,
   "food": 8,
   "morality": 0,
   "xp": null,
   "xp_amount": 0,
   "max_hp": 0,
   "phial": false
  },
  "fc:apple_pie": {
   "heal": 0,
   "will": 0,
   "food": 10,
   "morality": 0,
   "xp": null,
   "xp_amount": 0,
   "max_hp": 0,
   "phial": false
  },
  "fc:golden_carrot_brew": {
   "heal": 0,
   "will": 0,
   "food": 4,
   "morality": 0,
   "xp": null,
   "xp_amount": 0,
   "max_hp": 0,
   "phial": false
  }
 },
 "spells": {
  "enflame": {
   "name": "Enflame",
   "will": 15,
   "cd": 50,
   "align": 0,
   "desc": "A ring of fire erupts around the Hero."
  },
  "fireball": {
   "name": "Fireball",
   "will": 12,
   "cd": 30,
   "align": 0,
   "desc": "Hurl an explosive sphere of flame."
  },
  "lightning": {
   "name": "Lightning",
   "will": 14,
   "cd": 35,
   "align": 0,
   "desc": "Arc lightning leaps between your foes."
  },
  "force_push": {
   "name": "Force Push",
   "will": 10,
   "cd": 45,
   "align": 0,
   "desc": "A telekinetic blast hurls enemies away."
  },
  "drain_life": {
   "name": "Drain Life",
   "will": 16,
   "cd": 60,
   "align": -1,
   "desc": "Steal the life of those around you. (-5 morality)"
  },
  "heal_life": {
   "name": "Heal Life",
   "will": 18,
   "cd": 60,
   "align": 1,
   "desc": "Convert Will energy into vitality."
  },
  "physical_shield": {
   "name": "Physical Shield",
   "will": 12,
   "cd": 100,
   "align": 0,
   "desc": "A shell of Will absorbs harm while your energy lasts."
  },
  "slow_time": {
   "name": "Slow Time",
   "will": 20,
   "cd": 200,
   "align": 0,
   "desc": "The world crawls. You do not."
  },
  "assassin_rush": {
   "name": "Assassin Rush",
   "will": 8,
   "cd": 40,
   "align": 0,
   "desc": "Blink behind your target in a streak of shadow."
  },
  "summon": {
   "name": "Summon",
   "will": 25,
   "cd": 200,
   "align": 1,
   "desc": "Call a creature to fight at your side. (Good Heroes only)"
  },
  "turncoat": {
   "name": "Turncoat",
   "will": 18,
   "cd": 160,
   "align": 0,
   "desc": "Bend an enemy's mind to fight for you."
  },
  "multi_arrow": {
   "name": "Multi Arrow",
   "will": 10,
   "cd": 60,
   "align": 0,
   "desc": "Your next volley splits into a fan of arrows."
  },
  "multi_strike": {
   "name": "Multi Strike",
   "will": 12,
   "cd": 120,
   "align": 0,
   "desc": "Briefly strike with impossible speed."
  },
  "battle_charge": {
   "name": "Battle Charge",
   "will": 14,
   "cd": 80,
   "align": 0,
   "desc": "Charge forward, smashing all in your path."
  },
  "berserk": {
   "name": "Berserk",
   "will": 20,
   "cd": 240,
   "align": -1,
   "desc": "Rage swells your body and dims your mind."
  },
  "divine_fury": {
   "name": "Divine Fury",
   "will": 35,
   "cd": 300,
   "align": 1,
   "desc": "Holy radiance sears the wicked. (Good Heroes only)"
  },
  "infernal_wrath": {
   "name": "Infernal Wrath",
   "will": 35,
   "cd": 300,
   "align": -1,
   "desc": "Darkness devours all around you. (Evil Heroes only)"
  }
 },
 "upgrades": {
  "physique": {
   "id": "physique",
   "name": "Physique",
   "xp": "strength",
   "max": 5,
   "desc": "+melee damage, +size. Your shadow grows."
  },
  "health": {
   "id": "health",
   "name": "Health",
   "xp": "strength",
   "max": 5,
   "desc": "+max health per level."
  },
  "toughness": {
   "id": "toughness",
   "name": "Toughness",
   "xp": "strength",
   "max": 5,
   "desc": "+damage resistance."
  },
  "speed": {
   "id": "speed",
   "name": "Speed",
   "xp": "skill",
   "max": 5,
   "desc": "+movement and attack speed."
  },
  "guile": {
   "id": "guile",
   "name": "Guile",
   "xp": "skill",
   "max": 5,
   "desc": "+luck, +stealth, better trade prices."
  },
  "accuracy": {
   "id": "accuracy",
   "name": "Accuracy",
   "xp": "skill",
   "max": 5,
   "desc": "+ranged damage."
  },
  "magic_power": {
   "id": "magic_power",
   "name": "Magic Power",
   "xp": "will",
   "max": 5,
   "desc": "+max Will energy and Will regeneration."
  }
 },
 "quests": [
  {
   "id": "wasp_menace",
   "name": "The Wasp Menace",
   "chain": "main",
   "order": 1,
   "giver": "Guildmaster",
   "renown": 100,
   "desc": "Wasps swarm the picnic grounds. Slay the Wasp Queen before lunch is ruined forever.",
   "objectives": [
    {
     "type": "kill",
     "family": "fc_wasp",
     "count": 8,
     "label": "Slay 8 Wasps"
    },
    {
     "type": "kill",
     "family": "fc_wasp_queen",
     "count": 1,
     "label": "Destroy the Wasp Queen"
    }
   ],
   "rewards": {
    "gold": 200,
    "xp": {
     "general": 200,
     "strength": 50
    },
    "morality": 20,
    "items": [
     {
      "id": "fc:health_potion",
      "count": 2
     }
    ]
   },
   "next": "trader_escort"
  },
  {
   "id": "trader_escort",
   "name": "Trader Escort",
   "chain": "main",
   "order": 2,
   "giver": "Guildmaster",
   "renown": 150,
   "desc": "Traders vanish on the Darkwood road. Hunt the beasts that prey upon them.",
   "objectives": [
    {
     "type": "kill",
     "family": "fc_hobbe",
     "count": 10,
     "label": "Clear 10 Hobbes from the road"
    },
    {
     "type": "kill",
     "family": "fc_balverine",
     "count": 3,
     "label": "Slay 3 Balverines"
    }
   ],
   "rewards": {
    "gold": 400,
    "xp": {
     "general": 300,
     "strength": 80
    },
    "morality": 100,
    "items": [
     {
      "id": "fc:steel_longsword",
      "count": 1
     }
    ]
   },
   "next": "bandit_seeress"
  },
  {
   "id": "bandit_seeress",
   "name": "Find the Bandit Seeress",
   "chain": "main",
   "order": 3,
   "giver": "Guildmaster",
   "renown": 300,
   "desc": "Twinblade's camp shelters a seeress who knows your sister's fate. Cut your way to the truth.",
   "objectives": [
    {
     "type": "kill",
     "family": "fc_bandit",
     "count": 15,
     "label": "Defeat 15 of Twinblade's bandits"
    },
    {
     "type": "collect",
     "item": "fc:quest_card",
     "count": 1,
     "label": "Recover the camp orders"
    }
   ],
   "rewards": {
    "gold": 800,
    "xp": {
     "general": 500,
     "skill": 150
    },
    "morality": 0,
    "items": [
     {
      "id": "fc:obsidian_longsword",
      "count": 1
     }
    ]
   },
   "next": "arena_of_heroes"
  },
  {
   "id": "arena_of_heroes",
   "name": "The Arena",
   "chain": "main",
   "order": 4,
   "giver": "Nostro's Echo",
   "renown": 600,
   "desc": "Prove yourself in the Arena: waves of beasts, then the champion's purse.",
   "objectives": [
    {
     "type": "kill",
     "family": "fc_beetle",
     "count": 6,
     "label": "Round 1: 6 Beetles"
    },
    {
     "type": "kill",
     "family": "fc_hobbe",
     "count": 6,
     "label": "Round 2: 6 Hobbes"
    },
    {
     "type": "kill",
     "family": "fc_bandit",
     "count": 6,
     "label": "Round 3: 6 Bandits"
    },
    {
     "type": "kill",
     "family": "fc_balverine",
     "count": 4,
     "label": "Round 4: 4 Balverines"
    },
    {
     "type": "kill",
     "family": "fc_troll",
     "count": 1,
     "label": "Final Round: an Earth Troll"
    }
   ],
   "rewards": {
    "gold": 5000,
    "xp": {
     "general": 1200,
     "strength": 200,
     "skill": 200
    },
    "morality": 0,
    "items": [
     {
      "id": "fc:platemail_torso",
      "count": 1
     }
    ],
    "title": "Champion of the Arena"
   },
   "next": "find_the_oracle"
  },
  {
   "id": "find_the_oracle",
   "name": "Find the Oracle",
   "chain": "main",
   "order": 5,
   "giver": "Maze",
   "renown": 900,
   "desc": "The Oracle of Snowspire remembers all. The Northern Wastes will test you on the way.",
   "objectives": [
    {
     "type": "kill",
     "family": "fc_frost_balverine",
     "count": 3,
     "label": "Slay 3 Frost Balverines"
    },
    {
     "type": "kill",
     "family": "fc_summoner",
     "count": 4,
     "label": "Banish 4 Summoners"
    },
    {
     "type": "collect",
     "item": "fc:banshees_tear",
     "count": 1,
     "label": "Bottle a Banshee's Tear"
    }
   ],
   "rewards": {
    "gold": 2000,
    "xp": {
     "general": 1500,
     "will": 400
    },
    "morality": 0,
    "items": [
     {
      "id": "fc:septimal_key",
      "count": 1
     }
    ]
   },
   "next": "jack_of_blades"
  },
  {
   "id": "jack_of_blades",
   "name": "Battle Jack of Blades",
   "chain": "main",
   "order": 6,
   "giver": "Theresa",
   "renown": 2000,
   "desc": "He took your mother. He burned Oakvale. He waits in the Chamber of Fate, wearing his red smile.",
   "objectives": [
    {
     "type": "kill",
     "family": "fc_jack",
     "count": 1,
     "label": "Defeat Jack of Blades"
    },
    {
     "type": "kill",
     "family": "fc_jack_dragon",
     "count": 1,
     "label": "Slay the Dragon of Blades"
    }
   ],
   "rewards": {
    "gold": 10000,
    "xp": {
     "general": 5000,
     "strength": 500,
     "skill": 500,
     "will": 500
    },
    "morality": 0,
    "items": [
     {
      "id": "fc:sword_of_aeons",
      "count": 1
     }
    ],
    "title": "Hero of Oakvale"
   },
   "next": null
  },
  {
   "id": "hobbe_cave",
   "name": "The Hobbe Caves",
   "chain": "side",
   "order": 1,
   "giver": "Knothole Glade Elder",
   "renown": 120,
   "desc": "A child is lost in the Hobbe caves. Hobbes do terrible things to lost children.",
   "objectives": [
    {
     "type": "kill",
     "family": "fc_hobbe",
     "count": 12,
     "label": "Cull 12 cave Hobbes"
    }
   ],
   "rewards": {
    "gold": 350,
    "xp": {
     "general": 250
    },
    "morality": 60,
    "items": [
     {
      "id": "fc:silver_key",
      "count": 1
     }
    ]
   },
   "next": null
  },
  {
   "id": "graveyard_path",
   "name": "The Graveyard Path",
   "chain": "side",
   "order": 2,
   "giver": "Lychfield Gravekeeper",
   "renown": 150,
   "desc": "The dead of Lychfield refuse to stay buried. Put them down with respect \u2014 or without.",
   "objectives": [
    {
     "type": "kill",
     "family": "fc_undead",
     "count": 10,
     "label": "Lay 10 Hollow Men to rest"
    },
    {
     "type": "kill",
     "family": "fc_banshee",
     "count": 1,
     "label": "Silence the Banshee"
    }
   ],
   "rewards": {
    "gold": 500,
    "xp": {
     "general": 400,
     "will": 100
    },
    "morality": 40,
    "items": [
     {
      "id": "fc:ectoplasm",
      "count": 4
     }
    ]
   },
   "next": null
  },
  {
   "id": "white_balverine",
   "name": "The White Balverine",
   "chain": "side",
   "order": 3,
   "giver": "Knothole Glade Chief",
   "renown": 400,
   "desc": "A White Balverine stalks Knothole Glade. Ordinary steel will not bite \u2014 silver will.",
   "objectives": [
    {
     "type": "kill",
     "family": "fc_white_balverine",
     "count": 1,
     "label": "Slay the White Balverine"
    }
   ],
   "rewards": {
    "gold": 1500,
    "xp": {
     "general": 800,
     "strength": 200
    },
    "morality": 80,
    "items": [
     {
      "id": "fc:silver_augment",
      "count": 1
     },
     {
      "id": "fc:balverine_trophy",
      "count": 1
     }
    ]
   },
   "next": null
  },
  {
   "id": "lady_greys_invitation",
   "name": "Lady Grey's Invitation",
   "chain": "side",
   "order": 4,
   "giver": "Lady Grey",
   "renown": 250,
   "desc": "The Mayor of Bowerstone desires a gift: a black rose... or failing that, a great deal of gold.",
   "objectives": [
    {
     "type": "collect",
     "item": "fc:gold_coin",
     "count": 32,
     "label": "Gather a courting gift (32 gold coins)"
    },
    {
     "type": "collect",
     "item": "fc:wedding_ring",
     "count": 1,
     "label": "Acquire a Wedding Ring"
    }
   ],
   "rewards": {
    "gold": 0,
    "xp": {
     "general": 300
    },
    "morality": 0,
    "items": [
     {
      "id": "fc:katana_hiryu",
      "count": 1
     }
    ],
    "title": "Consort of Bowerstone"
   },
   "next": null
  },
  {
   "id": "treasure_of_the_keys",
   "name": "Treasure of the Keys",
   "chain": "side",
   "order": 5,
   "giver": "Silver Chest",
   "renown": 200,
   "desc": "Fifteen silver keys lie hidden in ruins across Albion. The great chest in the Guild waits.",
   "objectives": [
    {
     "type": "collect",
     "item": "fc:silver_key",
     "count": 15,
     "label": "Collect 15 Silver Keys"
    }
   ],
   "rewards": {
    "gold": 3000,
    "xp": {
     "general": 600
    },
    "morality": 0,
    "items": [
     {
      "id": "fc:arkens_crossbow",
      "count": 1
     }
    ]
   },
   "next": null
  },
  {
   "id": "bounty_bandit_king",
   "name": "Bounty: Bandit Lieutenants",
   "chain": "job",
   "order": 6,
   "giver": "Bowerstone Notice Board",
   "renown": 180,
   "desc": "Bowerstone pays good coin for bandit ears. Bring proof of your work.",
   "objectives": [
    {
     "type": "kill",
     "family": "fc_bandit",
     "count": 20,
     "label": "Collect the bounty: 20 bandits"
    }
   ],
   "rewards": {
    "gold": 1200,
    "xp": {
     "general": 350,
     "skill": 100
    },
    "morality": 30,
    "items": []
   },
   "next": null
  },
  {
   "id": "trophy_hunter",
   "name": "Trophy Hunter",
   "chain": "job",
   "order": 7,
   "giver": "Fresco Dove",
   "renown": 220,
   "desc": "A collector in Bowerstone pays for exotic remains. No questions either way.",
   "objectives": [
    {
     "type": "collect",
     "item": "fc:balverine_fang",
     "count": 8,
     "label": "8 Balverine Fangs"
    },
    {
     "type": "collect",
     "item": "fc:troll_heart",
     "count": 1,
     "label": "1 Troll Heart"
    },
    {
     "type": "collect",
     "item": "fc:wasp_wing",
     "count": 12,
     "label": "12 Wasp Wings"
    }
   ],
   "rewards": {
    "gold": 2000,
    "xp": {
     "general": 400
    },
    "morality": -20,
    "items": [
     {
      "id": "fc:experience_augment",
      "count": 1
     }
    ]
   },
   "next": null
  },
  {
   "id": "the_septimal_seal",
   "name": "The Septimal Seal",
   "chain": "side",
   "order": 8,
   "giver": "The Oracle",
   "renown": 500,
   "desc": "Awaken the Focus Sites. Carry the Septimal Key to their stones and feed them ectoplasm.",
   "objectives": [
    {
     "type": "collect",
     "item": "fc:ectoplasm",
     "count": 10,
     "label": "Gather 10 Ectoplasm"
    },
    {
     "type": "kill",
     "family": "fc_wraith",
     "count": 5,
     "label": "Banish 5 Wraiths"
    }
   ],
   "rewards": {
    "gold": 1000,
    "xp": {
     "will": 600,
     "general": 500
    },
    "morality": 0,
    "items": [
     {
      "id": "fc:summoners_grimoire",
      "count": 1
     }
    ]
   },
   "next": null
  }
 ],
 "demonDoors": [
  {
   "id": "gourmand",
   "name": "The Gourmand Door",
   "greeting": "Mmmm... I smell crumbs on you, little thing. FEED ME and we shall talk.",
   "requirement": {
    "type": "items",
    "item": "fc:apple_pie",
    "count": 5,
    "hint": "Bring me FIVE apple pies. Warm ones."
   },
   "success": "Ohhh, flaky! Buttery! WORTH ETERNITY. Enter, pastry-friend.",
   "fail": "That is NOT pie. Come back when you respect dessert.",
   "reward": {
    "items": [
     {
      "id": "fc:wellows_pickhammer",
      "count": 1
     },
     {
      "id": "fc:gold_coin",
      "count": 20
     }
    ],
    "xp": 250
   }
  },
  {
   "id": "warrior",
   "name": "The Warrior Door",
   "greeting": "I open for violence alone. Show me a Combat Multiplier worthy of the old days.",
   "requirement": {
    "type": "multiplier",
    "count": 14,
    "hint": "Return mid-battle with a Combat Multiplier of 14 or more."
   },
   "success": "YES! That is how heroes bled in MY day! Pass, slaughter-child.",
   "fail": "Pitiful. My hinges have seen scarier brawls.",
   "reward": {
    "items": [
     {
      "id": "fc:the_harbinger",
      "count": 1
     }
    ],
    "xp": 400
   }
  },
  {
   "id": "judge",
   "name": "The Judge Door",
   "greeting": "I weigh souls, Hero. Only the truly radiant may pass my arch.",
   "requirement": {
    "type": "morality_min",
    "count": 500,
    "hint": "Return when your goodness shines (Morality 500+)."
   },
   "success": "You glow like dawn over Oakvale. Pass, blessed one.",
   "fail": "Your soul is... beige. Do better.",
   "reward": {
    "items": [
     {
      "id": "fc:archon_torso",
      "count": 1
     },
     {
      "id": "fc:holy_warrior_helm",
      "count": 1
     }
    ],
    "xp": 350
   }
  },
  {
   "id": "corrupted",
   "name": "The Corrupted Door",
   "greeting": "I smell mercy on you. Disgusting. Only the vile may enter my dark.",
   "requirement": {
    "type": "morality_max",
    "count": -500,
    "hint": "Return drenched in wickedness (Morality -500 or worse)."
   },
   "success": "Ahhh, what beautiful rot in your heart. Welcome home.",
   "fail": "Too kind, too clean. Go drown a kitten and come back.",
   "reward": {
    "items": [
     {
      "id": "fc:demon_helm",
      "count": 1
     },
     {
      "id": "fc:fire_assassin_torso",
      "count": 1
     }
    ],
    "xp": 350
   }
  },
  {
   "id": "hoarder",
   "name": "The Hoarder Door",
   "greeting": "Gold. Gooooold. I am a door of simple tastes. PAY THE TOLL.",
   "requirement": {
    "type": "items",
    "item": "fc:gold_coin",
    "count": 50,
    "hint": "Feed my slot FIFTY gold coins."
   },
   "success": "Cha-CHING! A pleasure doing business, moneybags.",
   "fail": "Your purse whimpers. Come back wealthy.",
   "reward": {
    "items": [
     {
      "id": "fc:orkons_club",
      "count": 1
     },
     {
      "id": "fc:silver_key",
      "count": 2
     }
    ],
    "xp": 300
   }
  },
  {
   "id": "moonlit",
   "name": "The Moonlit Door",
   "greeting": "I open only beneath the moon, for those the night has marked.",
   "requirement": {
    "type": "night_multiplier",
    "count": 5,
    "hint": "Come at night, riding a Combat Multiplier of 5 or more."
   },
   "success": "The moon approves of your violence. Slip through, night-thing.",
   "fail": "The moon is bored of you. Return bloodier, and after dusk.",
   "reward": {
    "items": [
     {
      "id": "fc:avenger",
      "count": 1
     }
    ],
    "xp": 300
   }
  },
  {
   "id": "riddler",
   "name": "The Riddler Door",
   "greeting": "A game! I ask, you answer. Fail and I shall laugh at you for a century.",
   "requirement": {
    "type": "riddle",
    "riddle": "I have a face I cannot wash, a mouth that cannot eat, and I sing to no one before dawn. What am I?",
    "answers": [
     "A rooster",
     "A Demon Door",
     "A clock",
     "A grave"
    ],
    "correct": 2,
    "hint": "Answer my riddle correctly."
   },
   "success": "Tick-tock, clever clogs. The prize is yours.",
   "fail": "WRONG! Hahahaha. Think harder, fleshling.",
   "reward": {
    "items": [
     {
      "id": "fc:silver_key",
      "count": 5
     },
     {
      "id": "fc:summoners_grimoire",
      "count": 1
     }
    ],
    "xp": 300
   }
  },
  {
   "id": "arboretum",
   "name": "The Arboretum Door",
   "greeting": "I guard a garden older than your Guild. Only a seasoned soul may smell its roses.",
   "requirement": {
    "type": "renown",
    "count": 1000,
    "hint": "Return when Albion sings of your deeds (Renown 1000+)."
   },
   "success": "Your legend precedes you like perfume. Enter the green.",
   "fail": "Never heard of you. Do something worth a song.",
   "reward": {
    "items": [
     {
      "id": "fc:solus_greatsword",
      "count": 1
     },
     {
      "id": "fc:elixir_of_life",
      "count": 1
     }
    ],
    "xp": 500
   }
  }
 ],
 "killXp": {
  "fc_wasp": 6,
  "fc_beetle": 4,
  "fc_hobbe": 12,
  "fc_bandit": 18,
  "fc_undead": 15,
  "fc_balverine": 35,
  "fc_frost_balverine": 80,
  "fc_troll": 120,
  "fc_wraith": 45,
  "fc_banshee": 60,
  "fc_minion": 30,
  "fc_summoner": 55,
  "fc_assassin": 50,
  "fc_boss": 400,
  "fc_guard": 10,
  "fc_villager": 2,
  "fc_nymph": 5
 },
 "killMorality": {
  "fc_balverine": 8,
  "fc_frost_balverine": 12,
  "fc_undead": 6,
  "fc_wasp": 1,
  "fc_beetle": 0,
  "fc_hobbe": 3,
  "fc_bandit": 5,
  "fc_troll": 10,
  "fc_wraith": 6,
  "fc_banshee": 8,
  "fc_minion": 5,
  "fc_summoner": 6,
  "fc_assassin": 6,
  "fc_boss": 50,
  "fc_villager": -100,
  "fc_guard": -150,
  "fc_trader": -120,
  "fc_nymph": -20
 },
 "augments": {
  "fc:sharpening_augment": "sharpening",
  "fc:piercing_augment": "piercing",
  "fc:health_augment": "health",
  "fc:mana_augment": "mana",
  "fc:experience_augment": "experience",
  "fc:lightning_augment": "lightning",
  "fc:flame_augment": "flame",
  "fc:silver_augment": "silver"
 }
};
