"""Deterministic checklist progress; no inferred gameplay or canon grades."""
import argparse
from collections import Counter
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
CHECKLIST = Path('docs/CONFORMANCE_CHECKLIST.md')
AUDIT = Path('screenshots/structures/contract/AUDIT.md')
START, END = '<!-- conformance-score:start -->', '<!-- conformance-score:end -->'
DOMAINS = ('0', 'L', 'W', 'E', 'V', 'M', 'C')
IDS = {
    '0': [f'0.{n}' for n in range(1, 5)],
    'L': ['L1', 'L2', 'L3.1', 'L3.2', 'L3.3', 'L4'],
    'W': [f'W{group}.{n}' for group, count in ((1, 4), (2, 4), (3, 5), (4, 5)) for n in range(1, count + 1)],
    'E': [f'E{n}' for n in range(1, 5)],
    'V': [f'V{n}' for n in range(1, 5)],
    'M': [f'M{n}' for n in range(6)],
    'C': [f'C{n}' for n in range(1, 4)],
}
EXPECTED = {key for values in IDS.values() for key in values}
ID_PATTERN = re.compile(r'^(0\.\d+|[LWEVMC]\d+(?:\.\d+)?)\s+')


def parse(text, root=ROOT):
    rows = {}
    for line in text.splitlines():
        if not line.startswith('| '): continue
        cells = [cell.strip() for cell in line.strip().strip('|').split('|')]
        match = ID_PATTERN.match(cells[0])
        if not match: continue
        key = match[1]
        if key not in EXPECTED: raise ValueError(f'Unknown checklist ID: {key}')
        if key in rows: raise ValueError(f'Duplicate checklist ID: {key}')
        if len(cells) != 5: raise ValueError(f'Invalid checklist columns: {key}')
        label, status, evidence, grade, date = cells
        if status not in ('todo', 'in-progress', 'done'): raise ValueError(f'Invalid status: {key}: {status}')
        paths = []
        if evidence != '—':
            parts = evidence.split(';')
            commit = parts[0].strip()
            if not (re.fullmatch(r'[0-9a-f]{7,40}', commit) or commit.startswith(f'SELF: TLC Conformance — {key}: ')):
                raise ValueError(f'Invalid commit reference: {key}')
            for part in parts[1:]:
                relative = Path(part.strip())
                if relative.is_absolute() or '..' in relative.parts or not part.strip():
                    raise ValueError(f'Invalid evidence path: {key}: {part}')
                if not (root / relative).exists(): raise ValueError(f'Missing evidence path: {key}: {part.strip()}')
                paths.append(relative)
        if status != 'todo' and not paths: raise ValueError(f'Missing evidence: {key}')
        if status == 'done' and ('PENDING' in grade or 'BLOCKED' in grade): raise ValueError(f'Incomplete grade marked done: {key}')
        if status != 'todo' and not re.fullmatch(r'\d{4}-\d{2}-\d{2}', date): raise ValueError(f'Missing evidence date: {key}')
        rows[key] = {'status': status, 'grade': grade, 'label': label,
                     'automated': 'PASS (automated)' in grade or 'PASS (local + clean snapshot + GitHub CI)' in grade,
                     'manual_pending': 'PENDING (manual' in grade}
    missing = EXPECTED - rows.keys()
    if missing: raise ValueError('Missing checklist IDs: ' + ', '.join(sorted(missing)))
    return rows


def audit_grades(text):
    grades, seen = Counter(), set()
    for line in text.splitlines():
        if not line.startswith('| ') or line.startswith(('| ID |', '| --- |')): continue
        cells = [cell.strip() for cell in line.strip().strip('|').split('|')]
        if len(cells) != 5 or cells[1] not in ('S', 'A', 'B', 'C', 'D'): raise ValueError('Invalid structure audit grade row')
        if cells[0] in seen: raise ValueError('Duplicate structure audit ID')
        seen.add(cells[0]); grades[cells[1]] += 1
    if not seen: raise ValueError('Missing structure audit grades')
    return grades


def render(rows, grades):
    lines = [START, '', 'Generated by `python scripts/conformance_score.py --write`; CI checks for stale output.', '',
             '| Domain | Done / total | Completion | Automated PASS recorded | Manual pending recorded | In progress | Todo |',
             '| --- | --- | --- | --- | --- | --- | --- |']
    for domain in (*DOMAINS, 'Total'):
        keys = IDS[domain] if domain != 'Total' else list(EXPECTED)
        items = [rows[key] for key in keys]
        counts = Counter(item['status'] for item in items)
        lines.append(f"| {domain} | {counts['done']} / {len(items)} | {100 * counts['done'] / len(items):.1f}% | "
                     f"{sum(i['automated'] for i in items)} | {sum(i['manual_pending'] for i in items)} | "
                     f"{counts['in-progress']} | {counts['todo']} |")
    pending = [key for domain in DOMAINS for key in IDS[domain] if rows[key]['manual_pending']]
    lines += ['', 'Pending manual plan checks: ' + (', '.join(pending) if pending else 'none recorded') + '.', '',
              'Counts cover the 45 approved plan leaves. Spell/bootstrap prerequisites are listed',
              'separately above. Completion means a row is done; automated PASS can coexist with',
              'pending manual work. Todo rows have unknown verification, not an inferred pass.',
              'Manual counts reflect explicit grade cells; absence of a pending label is not proof',
              'that a feature has been tested in-world. The spell in-world checklist also remains separate.', '',
              'Current offline structure appearance grades from',
              '[the C2 audit](../screenshots/structures/contract/AUDIT.md): ' +
              ', '.join(f'{letter}={grades[letter]}' for letter in ('S', 'A', 'B', 'C', 'D')) + '.',
              'These are renderer metrics, not canon/playability grades. No letter-grade average',
              'or overall canon-conformance score is inferred.', '', END]
    return '\n'.join(lines)


def update(text, root=ROOT, check=False):
    if text.count(START) != 1 or text.count(END) != 1 or text.index(END) < text.index(START):
        raise ValueError('Missing, duplicate or reversed scoreboard markers')
    generated = render(parse(text, root), audit_grades((root / AUDIT).read_text()))
    before, rest = text.split(START); _, after = rest.split(END)
    result = before + generated + after
    if check and result != text: raise ValueError('Stale scoreboard; run python scripts/conformance_score.py --write')
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--write', action='store_true')
    args = parser.parse_args()
    path = ROOT / CHECKLIST
    try:
        result = update(path.read_text(), check=args.check)
    except (ValueError, OSError) as error:
        print(f'Conformance scoreboard: FAIL: {error}')
        return 1
    if args.write: path.write_text(result)
    print('Conformance scoreboard: PASS (45 plan leaves; manual/appearance evidence kept separate)')
    return 0


if __name__ == '__main__': raise SystemExit(main())
