"""Canonical Fable TLC expression registry used by the pack generators."""


def emote(eid, name, category, unlock, effect, template, functional="social"):
    return {
        "id": eid,
        "name": name,
        "category": category,
        "unlock": unlock,
        "effect": effect,
        "animation": f"animation.fable.player.{eid}",
        "template": template,
        "durationTicks": 40,
        "functional": functional,
        "nativePersonaPieceIds": [],
    }


EMOTES = [
    # Social expressions available from the start.
    emote("belch", "Belch", "funny", {"type": "start"},
          {"loveHate": -1, "fearFunny": -7, "uglyAttractive": -2, "morality": -1},
          "belch"),
    emote("fart", "Fart", "funny", {"type": "start"},
          {"loveHate": -2, "fearFunny": -10, "uglyAttractive": -3, "morality": -1},
          "fart"),
    emote("follow", "Follow", "friendly", {"type": "start"},
          {"loveHate": 4, "fearFunny": -1, "uglyAttractive": 0, "morality": 1},
          "beckon", "follow"),
    emote("wait", "Wait", "friendly", {"type": "start"},
          {"loveHate": 1, "fearFunny": 0, "uglyAttractive": 0, "morality": 0},
          "halt", "wait"),
    emote("giggle", "Giggle", "funny", {"type": "start"},
          {"loveHate": 2, "fearFunny": -7, "uglyAttractive": 1, "morality": 1},
          "laugh"),
    emote("flirt", "Flirt", "romantic", {"type": "start"},
          {"loveHate": 10, "fearFunny": -2, "uglyAttractive": 7, "morality": 2},
          "flirt"),
    emote("cossack_dance", "Cossack Dance", "funny", {"type": "start"},
          {"loveHate": 3, "fearFunny": -10, "uglyAttractive": 2, "morality": 1},
          "cossack"),

    # Renown ranks.
    emote("sneer", "Sneer", "scary", {"type": "renown", "rank": 1, "value": 100},
          {"loveHate": -3, "fearFunny": 8, "uglyAttractive": -1, "morality": -2},
          "sneer"),
    emote("manly_arm_pump", "Manly Arm Pump", "scary",
          {"type": "renown", "rank": 2, "value": 300},
          {"loveHate": 2, "fearFunny": 5, "uglyAttractive": 4, "morality": 0},
          "arm_pump"),
    emote("scary_laugh", "Scary Laugh", "scary",
          {"type": "renown", "rank": 3, "value": 700},
          {"loveHate": -3, "fearFunny": 12, "uglyAttractive": -1, "morality": -3},
          "scary_laugh"),
    emote("sexy_hero_pose", "Sexy Hero Pose", "romantic",
          {"type": "renown", "rank": 4, "value": 1200},
          {"loveHate": 8, "fearFunny": -1, "uglyAttractive": 10, "morality": 0},
          "hero_pose"),
    emote("blood_lust_roar", "Blood Lust Roar", "scary",
          {"type": "renown", "rank": 5, "value": 2000},
          {"loveHate": -6, "fearFunny": 16, "uglyAttractive": 1, "morality": -5},
          "roar"),

    # Alignment expressions.
    emote("apologise", "Apologise", "friendly", {"type": "alignment", "min": 150},
          {"loveHate": 9, "fearFunny": -1, "uglyAttractive": 2, "morality": 4},
          "apologise"),
    emote("air_guitar", "Air Guitar", "funny", {"type": "alignment", "max": -150},
          {"loveHate": 1, "fearFunny": -8, "uglyAttractive": 1, "morality": -2},
          "air_guitar"),
    emote("thanks", "Thanks", "friendly", {"type": "alignment", "min": 400},
          {"loveHate": 8, "fearFunny": -1, "uglyAttractive": 2, "morality": 3},
          "thanks"),
    emote("flamenco_dance", "Flamenco Dance", "funny",
          {"type": "alignment", "min": 400},
          {"loveHate": 4, "fearFunny": -9, "uglyAttractive": 4, "morality": 2},
          "flamenco"),
    emote("middle_finger", "Middle Finger", "rude",
          {"type": "alignment", "max": -400},
          {"loveHate": -12, "fearFunny": 2, "uglyAttractive": -4, "morality": -8},
          "rude"),
    emote("crotch_grab", "Crotch Grab", "funny", {"type": "alignment", "min": 750},
          {"loveHate": -2, "fearFunny": -9, "uglyAttractive": -3, "morality": 1},
          "crotch"),
    emote("disco_dance", "Disco Dance", "funny", {"type": "alignment", "min": 750},
          {"loveHate": 4, "fearFunny": -11, "uglyAttractive": 4, "morality": 2},
          "disco"),
    emote("vulgar_thrust", "Vulgar Thrust", "rude",
          {"type": "alignment", "max": -750},
          {"loveHate": -15, "fearFunny": 4, "uglyAttractive": -7, "morality": -10},
          "vulgar"),
    emote("kiss_my_ass", "Kiss My Ass", "rude", {"type": "alignment", "max": -400},
          {"loveHate": -11, "fearFunny": -2, "uglyAttractive": -5, "morality": -7},
          "kiss_ass"),
    emote("tap_dance", "Tap Dance", "funny", {"type": "alignment", "min": 400},
          {"loveHate": 3, "fearFunny": -9, "uglyAttractive": 3, "morality": 2},
          "tap"),

    # Guile expressions.
    emote("steal", "Steal", "criminal", {"type": "guile", "level": 3, "xp": 2200},
          {"loveHate": -9, "fearFunny": 3, "uglyAttractive": -2, "morality": -12},
          "steal", "steal"),
    emote("lockpick", "Lockpick", "criminal", {"type": "guile", "level": 6, "xp": 27400},
          {"loveHate": -5, "fearFunny": 2, "uglyAttractive": 0, "morality": -8},
          "lockpick", "lockpick"),

    # The Lost Chapters additions.
    emote("yeron", "Yeron", "oracle", {"type": "quest", "quest": "find_the_oracle"},
          {"loveHate": 1, "fearFunny": 1, "uglyAttractive": 1, "morality": 0},
          "oracle_yeron", "oracle"),
    emote("moryk", "Moryk", "oracle", {"type": "quest", "quest": "find_the_oracle"},
          {"loveHate": 1, "fearFunny": -1, "uglyAttractive": 1, "morality": 0},
          "oracle_moryk", "oracle"),
    emote("calran", "Calran", "oracle", {"type": "quest", "quest": "find_the_oracle"},
          {"loveHate": 1, "fearFunny": 1, "uglyAttractive": 0, "morality": 0},
          "oracle_calran", "oracle"),
    emote("avisto", "Avisto", "oracle", {"type": "quest", "quest": "find_the_oracle"},
          {"loveHate": 2, "fearFunny": 0, "uglyAttractive": 1, "morality": 0},
          "oracle_avisto", "oracle"),
    emote("ballet_dance", "Ballet Dance", "funny", {"type": "alignment", "min": 900},
          {"loveHate": 5, "fearFunny": -8, "uglyAttractive": 8, "morality": 3},
          "ballet"),
    emote("cock_a_doodle_doo", "Cock-A-Doodle-Doo", "funny",
          {"type": "challenge", "flag": "fc_chicken_champion"},
          {"loveHate": 2, "fearFunny": -12, "uglyAttractive": -1, "morality": 0},
          "chicken"),
    emote("insult", "Insult", "rude", {"type": "alignment", "max": -400},
          {"loveHate": -12, "fearFunny": 3, "uglyAttractive": -3, "morality": -8},
          "insult"),
]


assert len(EMOTES) == 31
