"""Own the HUD runtime output; edit templates/hud_runtime.js, then regenerate.

The inherited HUD module had no generator despite the ownership rule. The template
preserves its payload/clip contract; mode-dependent labels use generated fc_strings.js.
"""
from pathlib import Path
from fc_lib import BP, write_text

TEMPLATE = Path(__file__).parent / 'templates/hud_runtime.js'


def emit(bp=BP):
    write_text(bp / 'scripts/fable_hud.js',
               '// AUTO-GENERATED by scripts/gen_hud_runtime.py — do not edit.\n' +
               TEMPLATE.read_text(encoding='utf-8'))


if __name__ == '__main__':
    emit()
